version: "3.8"

services:
  vscode:
    build:
      context: .
      args:
        USER: ${USER}
        PASSWORD: ${PASSWORD}
        UID: ${UID}          # ← 추가
        GID: ${GID}          # ← 추가
    image: vscode-container:latest   # 이미지 이름 지정
    container_name: vscode-container
    ports:
      - "5002:5002"
    volumes:
      - ./dev:/home/${USER}/vscode # ← 로컬의 ./dev 폴더가 코드 저장소 -> vscode-server/dev 폴더가 컨테이너의 /home/user/vscode에 연결된다.
    environment:
      - PASSWORD=${PASSWORD}
    user: "${UID}:${GID}"   # ← 이 줄 추가
    restart: always
